#!/usr/bin/env python3
"""
Emit the two GENERATED tables inside ``AGENTS.md``:

  * §4  the core profile — operationId -> purpose, from the spec's
        ``x-protocol-core`` flags (the same flags ``PROFILE.md`` is built from)
  * §6  every ``reason_code`` with its remedy, from ``errors.json``

Why generated: both tables are the enumerations an agent is told to trust. A
hand-written copy of an enumeration is a copy that falls behind the thing it
enumerates — which is audit finding B1 in miniature, and it is exactly the
failure this file exists to prevent. The prose around the tables is written by
hand and left alone; only the regions between the markers below are replaced.

    python scripts/emit_agents.py            # rewrite the marked regions
    python scripts/emit_agents.py --check    # exit 1 if they are stale
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

AGENTS_PATH = os.path.join(REPO, 'AGENTS.md')
SPEC_PATH = os.path.join(REPO, 'spec', 'openapi.yaml')
ERRORS_PATH = os.path.join(REPO, 'errors.json')

#: Generated regions, keyed by marker name. Everything between
#: ``<!-- BEGIN:<name> -->`` and ``<!-- END:<name> -->`` is replaced.
BEGIN = '<!-- BEGIN:{} (generated by scripts/emit_agents.py — do not edit) -->'
END = '<!-- END:{} -->'

#: Tag -> the order it reads best in. A tag missing here sorts last, by name,
#: so a new family appears rather than disappearing.
TAG_ORDER = ('Grant', 'Discovery', 'Drill Holes', 'Drill Intervals', 'Samples',
             'Assays', 'Quality Control', 'STAC Catalog', 'Bulk Export')


def load_spec():
    import yaml
    with open(SPEC_PATH, encoding='utf-8') as fh:
        return yaml.safe_load(fh)


def core_operations(spec):
    """[(tag, operationId, METHOD, path, summary)] for every core operation."""
    rows = []
    for path, path_item in spec.get('paths', {}).items():
        for method, op in path_item.items():
            if not isinstance(op, dict) or method == 'parameters':
                continue
            if not op.get('x-protocol-core'):
                continue
            rows.append(((op.get('tags') or ['Other'])[0],
                         op.get('operationId', '?'), method.upper(), path,
                         (op.get('summary') or '').strip()))
    return rows


def profile_table(spec):
    rows = core_operations(spec)
    by_tag = {}
    for tag, oid, method, path, summary in rows:
        by_tag.setdefault(tag, []).append((oid, method, path, summary))

    def tag_key(tag):
        return (TAG_ORDER.index(tag) if tag in TAG_ORDER else len(TAG_ORDER), tag)

    out = [f'**{len(rows)} operations.** Everything else the server answers is '
           f'a geoDB extension: real and supported, but not part of the '
           f'contract another implementation is asked to serve. Which is which '
           f'is machine-readable — each operation in the spec carries '
           f'`x-protocol-core: true` or `x-geodb-extension: true`.', '']
    for tag in sorted(by_tag, key=tag_key):
        out.append(f'**{tag}**', )
        out.append('')
        out.append('| operationId | | Purpose |')
        out.append('|---|---|---|')
        for oid, method, path, summary in sorted(by_tag[tag]):
            out.append(f'| `{oid}` | `{method} {path}` | {summary} |')
        out.append('')
    return '\n'.join(out).rstrip()


def error_table():
    with open(ERRORS_PATH, encoding='utf-8') as fh:
        registry = json.load(fh)
    codes = registry['reason_codes']
    out = [f'**{len(codes)} codes.** Generated from '
           f'[`errors.json`](errors.json), which is itself generated from the '
           f'server, so this table cannot fall behind what you will actually '
           f'be refused with. Match on `reason_code`, never on `detail` prose.',
           '',
           '`retry` — **no**: retrying the identical request cannot succeed. '
           '**after**: retry once `Retry-After` has elapsed. **maybe**: '
           'transient or state-dependent, safe to retry later.',
           '',
           '| `reason_code` | HTTP | retry | What it means | What you do |',
           '|---|---|---|---|---|']
    for code, entry in sorted(codes.items(),
                              key=lambda kv: (kv[1]['http'], kv[0])):
        meaning = entry['meaning'].replace('\n', ' ').replace('|', '\\|')
        remedy = entry['remedy'].replace('\n', ' ').replace('|', '\\|')
        out.append(f'| `{code}` | {entry["http"]} | {entry["retry"]} | '
                   f'{meaning} | {remedy} |')
    return '\n'.join(out)


def regions():
    spec = load_spec()
    return {'core-profile': profile_table(spec), 'reason-codes': error_table()}


def rewrite(text, name, body):
    begin, end = BEGIN.format(name), END.format(name)
    if begin not in text or end not in text:
        raise SystemExit(
            f'AGENTS.md has no {name!r} region — expected the markers\n'
            f'  {begin}\n  {end}')
    head = text[:text.index(begin) + len(begin)]
    tail = text[text.index(end):]
    return f'{head}\n\n{body}\n\n{tail}'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='Exit 1 if a generated region is stale; write nothing.')
    args = ap.parse_args()

    with open(AGENTS_PATH, encoding='utf-8') as fh:
        original = fh.read()

    updated = original
    for name, body in regions().items():
        updated = rewrite(updated, name, body)

    if args.check:
        if updated != original:
            print('AGENTS.md is stale — a generated table no longer matches '
                  'spec/openapi.yaml or errors.json.')
            print('\nRun: python scripts/emit_agents.py')
            sys.exit(1)
        print('[OK] AGENTS.md generated tables match the spec and errors.json.')
        return

    if updated == original:
        print('  (AGENTS.md already current)')
        return
    with open(AGENTS_PATH, 'w', encoding='utf-8') as fh:
        fh.write(updated)
    print(f'  regenerated AGENTS.md ({", ".join(regions())})')


if __name__ == '__main__':
    main()
